name: CI build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.3', '8.4', '8.5']
        symfony: ['7.4.*', '8.0.*']
        deps: ['', '--prefer-lowest']
        exclude:
          # Symfony 8 requires PHP >= 8.4
          - php: '8.2'
            symfony: '8.0.*'
          - php: '8.3'
            symfony: '8.0.*'

    name: PHP ${{ matrix.php }} â€“ Symfony ${{ matrix.symfony }} ${{ matrix.deps }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          ini-values: memory_limit=-1

      - name: Configure Symfony version
        run: composer require --no-update \
          symfony/framework-bundle=${{ matrix.symfony }} \
          symfony/twig-bundle=${{ matrix.symfony }}

      - name: Install dependencies
        run: composer update --no-interaction --no-progress --prefer-dist ${{ matrix.deps }}

      - name: Run tests
        run: vendor/bin/phpunit
